### ISSUE TITLE
Help.q defines a new Q keyword that breaks other librarys

### ISSUE THREAD

**Issue by NathanSwann-AquaQ** [DataIntellectTech/TorQ#557]
Currently in [help.q](https://github.com/AquaQAnalytics/TorQ/blob/master/code/common/help.q) at the bottom there is the following definition:
```
349 | .q.help:.help.display
```
Which makes a new keyword `help` that then leads into issues when using other KDB library's at the same time as TorQ. For instance embedpy defines a function `help` in .p.q however due to the fact that `help` has become a keyword in help.q this definition now fails and in turn causes TorQ processes to fail to start.
```
2023.03.07D12:10:39.551058000|homer.aquaq.co.uk|rs|rs1|INF|fileload|loading /home/nswann/deploy/code/rs/rs.q
'assign
  [16] /home/nswann/deploy/embedPy/p.q:84: help:{[gh;h;x]if[10=type u:gh[h]x;-2 u]}[gethelp]import[`builtins;`:help]
                                                               ^
q.p))
```
I believe `.q.help` should either be changed to `.q.torqhelp` or removed from the `.q` namespace all together

**Comment by drewsteele** [comment]
👍 - this also causes issue when `help` is a parameter in an external function
```
q)myFunc:{[param1; help] 1+1 }
'type
  [1]  myFunc:{[param1; help] 1+1 }
       ^
```
