### ISSUE TITLE
Permissions framework does not work with lambdas as strings

### ISSUE THREAD

**Issue by erichards97** [DataIntellectTech/TorQ#579]
Passing lambdas as strings over IPC is valid in q:
![image](https://github.com/DataIntellectTech/TorQ/assets/30480510/a4110ade-50a3-419e-b3a4-721f2cbdfc90)

The popular VS Code extension, vscode-q, depends on this.

However a TorQ process with permissions enabled does not accept this - it converts the stringified-lambda to a symbol, then fails to recognise it (_parsequery_ --> _destringf_ --> .... --> _isvar_ --> _get_ fails leading to an error):
![image](https://github.com/DataIntellectTech/TorQ/assets/30480510/1968fd0a-5273-44da-84f3-47d961e9d132)

{...} and "{...}" should be treated the same. I will raise a PR for this.

**Comment by erichards97** [comment]
https://github.com/DataIntellectTech/TorQ/pull/582

**Comment by jonathonmcmurray** [comment]
#582 merged, closing
