### ISSUE TITLE
Permissions framework uses API code not loaded by tickerplants

### ISSUE THREAD

**Issue by erichards97** [DataIntellectTech/TorQ#580]
Enabling the permissions framework in a vanilla install of TorQ/finance starter pack fails, because it uses code in the .api namespace which isn't loaded by the tickerplants.

**Comment by erichards97** [comment]
Perhaps this isn't a bug as such because you wouldn't want the tickerplant to run the permissions framework due to the added latency incurred on each upd call. If someone could confirm this, that would be much appreciated.

**Comment by jonnypress** [comment]
Hi @erichards97. Yes your latter point is correct. Generally we want to keep the TP component as slim as possible. Ideally the tickerplant should be segregated from the rest of the environment, i.e. standard users can't connect to it and potentially do something stupid - they should only be able to hit the query components (e.g. rdb/hdb/gateway). There is still a vulnerability of course, e.g. if they can query the rdb they might be able to grab the TP handle and send a request, but that's a bit less accidental, and a lot of the permissions piece is about avoiding and controlling accidental or unsafe usage as opposed to stopping genuinely bad actors. 

If we wanted it in the TP itself we need to have a pre-check e.g. something like 

`if[.z.w in ListOfAllowedSystemInboundConnections; value x ; permissioncheck[x]]`

but even that has a cost.
