### ISSUE TITLE
Handlers should be loaded from appcode

### ISSUE THREAD

**Issue by erichards97** [DataIntellectTech/TorQ#581]
Currently handlers is only loaded from KDBCODE/KDBSERVCODE. It should also be loaded from KDBAPPCODE, if present, to allow customizations.
I will raise a PR for this.

**Comment by erichards97** [comment]
https://github.com/DataIntellectTech/TorQ/pull/583

**Comment by jonathonmcmurray** [comment]
#583 merged, closing
