### ISSUE TITLE
Permissions framework throws type error for projections

### ISSUE THREAD

**Issue by erichards97** [DataIntellectTech/TorQ#591]
![image](https://github.com/DataIntellectTech/TorQ/assets/30480510/d760f320-eeb7-4c74-beee-703328f0debb)

The left pane shows a TorQ process with pm enabled. The right shows a vanilla q process connecting to the TorQ process with admin credentials, which should have full access.

Calling a regular function with args (fn1) works fine, but calling a projected function with args (fn2) throws a type error.

The type error comes from `.pm.pdict`, specifically `fp!a` [here](https://github.com/DataIntellectTech/TorQ/blob/master/code/handlers/permissions.q#L79).
The error is recreated below using the last values that `.pm.pdict` was called with from the first screenshot
![image](https://github.com/DataIntellectTech/TorQ/assets/30480510/9e49d35d-b948-4932-95fc-fb769e749227)

In other instances, `.pm.pdict` returns a dictonary of parameter names to arguments. What is the intention with projections? Should it be trying to extract the fixed parameter and argument from the projection, and join this to the user provided args?

I'm happy to raise a PR for this but not entirely clear what the expected behaviour should be. Thanks 🙂

**Comment by jonathonmcmurray** [comment]
Thanks @erichards97, we'll have a look into this

**Comment by erichards97** [comment]
Given the projection has been defined on the server, I don't think the projected parameter(s) should need to be checked for client permissions, since the client would need to have been granted access to the projection/function in order to be able to call it in the first place. 

So perhaps `.pm.pdict` should create a dict of the remaining, un-projected param names and the user-provided args?

**Comment by jonathonmcmurray** [comment]
@erichards97 this issue should be fixed now via PR #593

**Comment by erichards97** [comment]
Thank you!
