### ISSUE TITLE
'domain error if more partitions than .merge.partlimit with writedownmode:`partbyenum

### ISSUE THREAD

**Issue by jonathonmcmurray** [DataIntellectTech/TorQ#668]
As per title, if more partitions (i.e. more enums) than `.merge.partlimit` when using ``writedownmode:`partbyenum``, we get a `'domain` error in `.merge.getpartchunks`.

It should be trivial to reproduce this issue by setting a low `.merge.partlimit` value & triggering EOD.

**Comment by mchbrn-q** [comment]
Recreated error using the old `l` expression referenced in issue [#669](https://github.com/DataIntellectTech/TorQ/issues/669). In previously using the full list of indexes from `.merge.partsizes`, `cut` throws a `'domain` error as these indexes exceed the number of `ptdir`'s in `t`. Therefore unrelated to .merge.partlimit, which is working as expected, and Joe's fix to the foregoing issue has also resolved this one
