### ISSUE TITLE
Support immediate writing in WDB

### ISSUE THREAD

**Issue by jonathonmcmurray** [DataIntellectTech/TorQ#679]
The WDB writedown works by periodically checking if the count of records in tables exceeds a configured rowcount, and writing down if so. If a user wishes to savedown every time the check runs, the obvious solution is to set the rowcount to 0 so that the check is always true and writedown always occurs.

However, this rowcount is also used during log replay https://github.com/DataIntellectTech/TorQ/blob/4a26653710e329a385e754c5872e8f12c3945402/code/processes/wdb.q#L551

which will lead to WDB writing to disk for every message in TP log if rowcount is set to 0. This will lead to a very slow recovery, so we should implement some logic to set the rowcount to zero only _after_ replay

**Comment by mchbrn-q** [comment]
[TorQ_679](https://github.com/DataIntellectTech/TorQ/pull/680)
